jobs:
  docker-job:
    steps:
        - name: show TAG
          run: echo ${{secrets.IMAGE_TAG}}
        - name: Setup
          uses: docker/setup-buildx-action@v2
        - name: Docker login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: alectrion/repo:${{secrets.IMAGE_TAG}}
