name: Build
on:
 push:
   branches:
     - main
     - develop
     - config/ci-cd
jobs:
  # sonarcloud:
  #   name: SonarCloud
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0 
  #     - name: Install dependencies
  #       run: yarn
  #     - name: Test and coverage
  #       run: yarn test:coverage
  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  #         SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  deploy:
    name: Deploy
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: show TAG
        run: echo ${{secrets.IMAGE_TAG}}
      - name: Setup
        uses: docker/setup-buildx-action@v2
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: alectrion/repo:${{secrets.IMAGE_TAG}}