name: Build
on:
 push:
   branches:
     - config/ci-cd
     - develop
 pull_request:
  branches:
     - main
jobs:
  sonarcloud:
    if: github.ref == 'refs/heads/develop'
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: yarn
      - name: Test and coverage
        run: yarn test:coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

  deploy:
    name: Image deploy
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: docker/setup-buildx-action@v2
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: alectrion/repo:${{secrets.IMAGE_TAG}}