name: Build
on:
 push:
   branches:
     - main
     - develop
     - config/ci-cd
jobs:
  # sonarcloud:
  #   name: SonarCloud
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0 
  #     - name: Install dependencies
  #       run: yarn
  #     - name: Test and coverage
  #       run: yarn test:coverage
  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  #         SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  deploy:
    name: Deploy
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/action.yml