name: collect-sonar-metric
on:
 release:
  types:
    - published

jobs:
  merged_in_main:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Get metrics and commit
      run: |
        mkdir analytics-raw-data
        curl "${{secrets.URL_METRICS}}" > analytics-raw-data/fga-eps-mds-2022-1-Alectrion-UserAPI-$(date +'%m-%d-%Y-%H-%M-%S')-${{github.event.release.tag_name}}.json
    - name: push metrics
      run: |
        git config --global user.email "${{secrets.GIT_USER_EMAIL}}"
        git config --global user.name "${{secrets.GIT_USER_NAME}}"
        git clone --single-branch --branch main "https://x-access-token:${{secrets.API_TOKEN_GITHUB}}@github.com/fga-eps-mds/2022-1-Alectrion-DOC" 2022-1-Alectrion-DOC
        cp -R analytics-raw-data/*.json 2022-1-Alectrion-DOC/analytics-raw-data/
        cd 2022-1-Alectrion-DOC
        git add .
        git commit -m "doc: adiciona metricas do ${{ github.event.repository.name }} release ${{github.event.release.tag_name}}"
        git push